import os
import asyncio
import time
from litellm import acompletion, exceptions
from dotenv import load_dotenv

load_dotenv()

# THE ABSOLUTE TRUTH: Confirmed working models from your ListModels diagnostics
CONFIRMED_GROQ = [
    "groq/llama-3.3-70b-versatile",
    "groq/llama-3.1-8b-instant",  # High rate limit, perfect backup
]

CONFIRMED_GEMINI = [
    "gemini/gemini-2.5-flash",    # Your key confirmed this as top choice
    "gemini/gemini-2.0-flash",    # Your second confirmed choice
    "gemini/gemini-2.5-flash-lite"
]

def get_prioritized_models():
    final_list = []
    # Groq first (Strict Priority)
    if os.getenv("GROQ_API_KEY"):
        final_list.extend(CONFIRMED_GROQ)
    
    # Gemini second (Reliable Fallback)
    if os.getenv("GEMINI_API_KEY"):
        final_list.extend(CONFIRMED_GEMINI)
        
    return final_list

DEFAULT_FALLBACKS = get_prioritized_models()

async def smart_completion(messages, temperature=0.1, model=None):
    """
    THE TANK-PROOF ORCHESTRATOR
    - Strict Priority: Always attempts Groq 70B -> Groq 8B -> Gemini 2.5.
    - Explicit Rate Limit Handling: Waits 2 seconds on 429/503 before retrying.
    - Verified Model Pool: Only uses models confirmed available for YOUR account.
    """
    if not DEFAULT_FALLBACKS:
        raise ValueError("CRITICAL: No valid API keys found in .env")

    # Always start with the top model (Groq 70B)
    primary_model = DEFAULT_FALLBACKS[0]
    fallbacks = DEFAULT_FALLBACKS[1:]
    
    max_attempts = 5
    for attempt in range(max_attempts):
        try:
            print(f"[AI_ORCHESTRATOR] Attempt {attempt+1}/{max_attempts} using: {primary_model}")
            
            response = await acompletion(
                model=primary_model,
                messages=messages,
                temperature=temperature,
                fallbacks=fallbacks,
                num_retries=2 # LiteLLM's internal retry
            )
            
            print(f"[AI_ORCHESTRATOR] SUCCESS: Response generated by {response.model}")
            return response

        except (exceptions.RateLimitError, exceptions.ServiceUnavailableError) as e:
            # If we hit a limit, we wait and then try again (likely falling back to next model)
            wait_time = 2 * (attempt + 1)
            print(f"[AI_ORCHESTRATOR] LIMIT_REACHED: Waiting {wait_time}s... (Error: {str(e)})")
            await asyncio.sleep(wait_time)
            continue
            
        except Exception as e:
            # Fatal error (e.g. invalid request) - don't retry, just raise
            print(f"[AI_ORCHESTRATOR] FATAL_ERROR: {str(e)}")
            raise e

    raise exceptions.ServiceUnavailableError("All models in the chain exhausted after 5 attempts.")
