import json
import argparse
import os
from src.database.db_utils import Neo4jClient

def create_document_node(tx, doc_name):
    query = """
    MERGE (d:Document {name: $doc_name})
    RETURN d
    """
    tx.run(query, doc_name=doc_name)

def create_section_node(tx, node_data, parent_id=None, doc_name=None):
    node_id = node_data.get('node_id', '')
    title = node_data.get('title', '')
    start_index = node_data.get('start_index', -1)
    end_index = node_data.get('end_index', -1)
    summary = node_data.get('summary', '')
    text = node_data.get('text', '')

    query = """
    MERGE (s:Section {node_id: $node_id, doc_name: $doc_name})
    SET s.title = $title,
        s.start_index = $start_index,
        s.end_index = $end_index,
        s.summary = $summary,
        s.text = $text
    RETURN s
    """
    tx.run(query, node_id=node_id, title=title, start_index=start_index, 
           end_index=end_index, summary=summary, text=text, doc_name=doc_name)

    if parent_id:
        link_query = """
        MATCH (p:Section {node_id: $parent_id, doc_name: $doc_name})
        MATCH (c:Section {node_id: $node_id, doc_name: $doc_name})
        MERGE (p)-[:HAS_SUBSECTION]->(c)
        """
        tx.run(link_query, parent_id=parent_id, node_id=node_id, doc_name=doc_name)
    elif doc_name:
        link_query = """
        MATCH (d:Document {name: $doc_name})
        MATCH (s:Section {node_id: $node_id, doc_name: $doc_name})
        MERGE (d)-[:HAS_SECTION]->(s)
        """
        tx.run(link_query, doc_name=doc_name, node_id=node_id)


def process_node(tx, node, parent_id=None, doc_name=None):
    if 'node_id' not in node:
        print(f"Warning: Node missing node_id. Title: {node.get('title')}. Skipping.")
        return

    create_section_node(tx, node, parent_id=parent_id, doc_name=doc_name)

    if 'nodes' in node and isinstance(node['nodes'], list):
        for child in node['nodes']:
            process_node(tx, child, parent_id=node['node_id'], doc_name=doc_name)

def ingest_json(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    doc_name = data.get('doc_name', os.path.basename(json_path))
    structure = data.get('structure', [])

    if not structure:
        print(f"No structure found in {json_path}")
        return

    neo4j_client = Neo4jClient()
    
    try:
        with neo4j_client.driver.session() as session:
            session.execute_write(create_document_node, doc_name)
            
            for root_node in structure:
                session.execute_write(process_node, root_node, parent_id=None, doc_name=doc_name)
                
        print(f"Successfully ingested {doc_name} into Neo4j.")
        
        import asyncio
        from src.database.reference_extractor import build_cross_references
        asyncio.run(build_cross_references(doc_name))
        
    except Exception as e:
        print(f"Error ingesting into Neo4j: {e}")
    finally:
        neo4j_client.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ingest PageIndex structure JSON into Neo4j")
    parser.add_argument("--json_path", type=str, required=True, help="Path to the JSON file generated by PageIndex")
    args = parser.parse_args()
    
    ingest_json(args.json_path)
